FROM debian:stable-slim

RUN mkdir /app
WORKDIR /app

RUN apt-get update
RUN apt-get install -y ca-certificates

# Cleaning up
RUN apt-get autoremove -y
RUN apt-get clean -y
RUN rm -rf /var/lib/apt/lists/

COPY saga_coordinator_runner /app
EXPOSE 8004

ENTRYPOINT ["/app/saga_coordinator_runner"]
