FROM debian:stable-slim

RUN mkdir /app
WORKDIR /app

RUN apt-get update && \
    apt-get install -y ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/

COPY saga_coordinator_runner /app
EXPOSE 8004

ENTRYPOINT ["/app/saga_coordinator_runner"]
