version: '3'
services:
  saga:
    image: saga
    build:
      context: .
      dockerfile: Dockerfile.saga
    container_name: saga
    working_dir: /app
    command: cargo run
    volumes:
      - ..:/app
      - stq_cargo_cache:/usr/local/cargo
    environment:
      - STQ_USERS_ADDR=http://users:8000
      - STQ_STORES_ADDR=http://stores:8000
      - "RUST_LOG=saga_coordinator=debug"
    ports:
      - "8000"
    expose:
      - 8000
    stdin_open: true

volumes:
  stq_cargo_cache:

networks:
  default:
    external:
      name: storiqa
