listen = "0.0.0.0:8000"
users_addr = "http://users:8000"
stores_addr = "http://stores:8000"
warehouses_addr = "http://warehouses:8000"
orders_addr = "http://orders:8000"
billing_addr = "http://billing:8000"
notifications_addr = "http://notifications:8000"
