[server]
host = "0.0.0.0"
port = "8000"

[users_microservice]
url="http://users:8000"

[stores_microservice]
url="http://stores:8000"

[orders_microservice]
url="http://orders:8000"

[billing_microservice]
url="http://billing:8000"

[warehouses_microservice]
url="http://warehouses:8000"

[notifications_microservice]
url="http://notifications:8000"

[delivery_microservice]
url="http://delivery:8000"

[graylog]
addr = "udplog.stq.cloud:32303"

[cluster]
url = "http://nightly.stq.cloud"

[notification_urls]

  [notification_urls.verify_email]
  web = "https://localhost/verify_email"
  ios = "storiqawallet://localhost/verify_email"
  android = "storiqawallet://localhost/verify_email"

  [notification_urls.reset_password]
  web = "https://localhost/verify_email"
  ios = "storiqawallet://localhost/verify_email"
  android = "storiqawallet://localhost/verify_email"

[client]
http_client_buffer_size = 10
http_client_retries = 3
http_timeout_ms = 15000

# [service]
# processing_timeout_ms = 1000
